README.md
marsiitr/Wall-Climbing-Robot pull request #1
Opened 2020-07-28 09:11 UTC by Monty-00

2020-07-28 11:37 UTC, SanjeevKrishnan requested changes
@Monty-00 Changes required
1. Rename "images and videos" as "Images and Videos"
2. Images and Videos should contain two sub-folders "Images" and "Videos".
3. File names should be self-explanatory. For ex., you are not allowed to have names like "IMG-20200728-WA0000.jpg".
4. Rename folder "Wall climbing" as "Mechanical Design".
5. Add CAD images(snapshots in .jpg format) of Solidworks files inside Mechanical Design folder.
6. Poster and Report is missing. Create a folder named "Poster and Report" and add one project report and one project preview poster inside that folder.
7. In README.md, add flowchart.
8. In README.md, hyperlink Team Member names and Mentor names with their GitHub profile link.

2020-07-29 10:22 UTC, Shubhanshu07 commented
> @Monty-00 Changes required
> 
> 1. Rename "images and videos" as "Images and Videos"
> 2. Images and Videos should contain two sub-folders "Images" and "Videos".
> 3. File names should be self-explanatory. For ex., you are not allowed to have names like "IMG-20200728-WA0000.jpg".
> 4. Rename folder "Wall climbing" as "Mechanical Design".
> 5. Add CAD images(snapshots in .jpg format) of Solidworks files inside Mechanical Design folder.
> 6. Poster and Report is missing. Create a folder named "Poster and Report" and add one project report and one project preview poster inside that folder.
> 7. In README.md, add flowchart.
> 8. In README.md, hyperlink Team Member names and Mentor names with their GitHub profile link.

@Monty-00  Do the following changes and tag me or @SanjeevKrishnan once you ar done with this

2020-07-29 13:28 UTC, SanjeevKrishnan requested changes
@Monty-00 Changes Required
1. Few file names in Mechanical Design folder are not self-explanatory. For ex., CAD Design 1, CAD Design2,   Make sure that name is matching with its respective solidwork file.
2. Flowchart is missing in README.md

2020-07-29 13:28 UTC, SanjeevKrishnan commented on README.md
> +1. Monty (https://github.com/Monty-00)
The syntax is wrong. It should be `[Monty](https://github.com/Monty-00)`. Change this for all members and mentors

2020-07-30 10:11 UTC, SanjeevKrishnan approved these changes
@Monty-00 All requirements are met! PR looks fine.
@Shubhanshu07 I suggest for merge.

2020-07-30 10:46 UTC, Shubhanshu07 commented
@Monty-00 Great Work Guys!!

2020-07-30 10:46 UTC, merged

2020-07-30 10:56 UTC, Shubhanshu07 commented
@Monty-00 Make a new PR.